# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', tinymce.models.HTMLField()),
                ('githublink', models.CharField(max_length=255)),
                ('weblink', models.CharField(max_length=255)),
                ('screenshot', pyuploadcare.dj.models.ImageField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techlogo', pyuploadcare.dj.models.ImageField()),
                ('technologies', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='myportfolio.Technology'),
        ),
    ]
